// This file is generated by tools/generate_articles_data.py
window.ARTICLE_INDEX = [
  {
    "href": "Article-7.html",
    "title": "My TOP 3 Movie",
    "date": "2026-04-03",
    "summary": "Movies, Personal Favorites",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-8.html",
    "title": "Abstract Accepted for JpGU-AGU Joint Meeting 2026",
    "date": "2026-04-03",
    "summary": "Conference, Oral Presentation, JpGU, AGU",
    "categories": [
      "conference"
    ]
  },
  {
    "href": "Article-15.html",
    "title": "My Top 5 TV Series",
    "date": "2026-04-02",
    "summary": "TV series, Personal Favorites",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-6.html",
    "title": "Japan Geoscience Union Meeting 2026",
    "date": "2026-02-09",
    "summary": "Conference-related pages and updates for my participation in the JpGU-AGU Joint Meeting 2026.",
    "categories": [
      "conference"
    ]
  },
  {
    "href": "Article-5.html",
    "title": "Gauss 2025 Reflection",
    "date": "2025-12-31",
    "summary": "A year marked by research, conferences, friendships, and a series of small moments that made 2025 feel both busy and...",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-4.html",
    "title": "Japan Geoscience Union Meeting 2025",
    "date": "2025-12-17",
    "summary": "Conference-related pages and updates for my participation in the Japan Geoscience Union Meeting 2025.",
    "categories": [
      "conference"
    ]
  },
  {
    "href": "Article-2.html",
    "title": "Goodbye, 2024 — A Letter To Myself, A Reflection",
    "date": "2025-01-01",
    "summary": "A personal walk through the months of 2024, from quiet ordinary days to the moments that ended up shaping my year more...",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-3.html",
    "title": "November Sky",
    "date": "2024-12-01",
    "summary": "November began with an endless Ising Model simulation. Then everyone started arguing about that overpass.",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-9.html",
    "title": "整個城市，都是我的自習室",
    "date": "2024-05-04",
    "summary": "四月的暴雨、五月的太陽，都讓人只想待在有空調的室內。前幾天開車經過國圖才發現我已經好幾年沒進國圖自習室了。",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-10.html",
    "title": "Let the Whole City be My Library",
    "date": "2024-05-04",
    "summary": "April downpours and May sunshine both make you want to stay somewhere air-conditioned.",
    "categories": [
      "translation"
    ]
  },
  {
    "href": "Article-11.html",
    "title": "改變聽音樂的習慣",
    "date": "2022-08-08",
    "summary": "在串流音樂幾乎壟斷一切的時代，重新思考我們如何聽音樂，也許不只是個人習慣問題，而是和創作者、載體與專輯本身都有關。",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-12.html",
    "title": "Changing the Way We Listen to Music",
    "date": "2022-08-08",
    "summary": "In an age when streaming seems to have absorbed music entirely, it may be worth asking whether the way we listen also...",
    "categories": [
      "translation"
    ]
  },
  {
    "href": "Article-13.html",
    "title": "臺北市兜風指南",
    "date": "2021-12-12",
    "summary": "如果兜風是一種讓人暫時脫離現實、重新感受城市與自己的方式，那麼在臺北，選對時間與道路就非常重要。",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-14.html",
    "title": "A Guide to Driving Around Taipei",
    "date": "2021-12-12",
    "summary": "If driving with no destination in mind is a way of stepping outside ordinary life for a while, then in Taipei the right...",
    "categories": [
      "translation"
    ]
  }
];
