// This file is generated by tools/generate_articles_data.py
window.ARTICLE_INDEX = [
  {
    "href": "Article-22.html",
    "title": "What We Lose in Motion: Quantifying Image Degradation in Photo-to-Video Conversion",
    "date": "2026-08-21",
    "meta": "Video Compression, H.264, Instagram Story, Chroma Subsampling, Image Fidelity, Temporal Stacking",
    "summary": "The moment you attach a background track to a crisp photo on Instagram Story, the image visibly degrades.",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-21.html",
    "title": "SCEC TPV102 Tatva vs. UGUCA vs. SPECFEM3D (standard mesh 100m)",
    "date": "2026-08-13",
    "meta": "Simulation, SCEC, TPV102, Tatva, UGUCA, SPECFEM3D",
    "summary": "A validation log comparing Tatva against UGUCA and SPECFEM3D for the SCEC TPV102 benchmark using the standard 100 m...",
    "categories": [
      "research"
    ]
  },
  {
    "href": "Article-20.html",
    "title": "SCEC TPV101 Tatva vs. UGUCA vs. SPECFEM3D (standard mesh 100m)",
    "date": "2026-08-12",
    "meta": "Simulation, SCEC, TPV101, Tatva, UGUCA, SPECFEM3D",
    "summary": "A validation log comparing Tatva against UGUCA and SPECFEM3D for the SCEC TPV101 benchmark using the standard 100 m...",
    "categories": [
      "research"
    ]
  },
  {
    "href": "Article-19.html",
    "title": "Nonlocal Elastic Unloading as a Mechanism for Breakdown Work Scaling in Laboratory Earthquakes",
    "date": "2026-07-31",
    "meta": "Rupture Dynamics, Laboratory Earthquakes, Breakdown Work, Fracture Energy",
    "summary": "Our latest paper examines why breakdown work can scale strongly with slip even when near-front dissipation remains low...",
    "categories": [
      "research"
    ]
  },
  {
    "href": "Article-18.html",
    "title": "JpGU 25 & 26 and some Graduation Frames",
    "date": "2026-07-02",
    "meta": "JpGU, Graduation, Film Photography, Travel Notes",
    "summary": "These are scanned frames from my 2025 and 2026 JpGU trips in Japan, mixed with a few graduation photographs and the...",
    "categories": [
      "conference"
    ]
  },
  {
    "href": "Article-17.html",
    "title": "Verbatim: A Local macOS App for Audio and Video Transcription",
    "date": "2026-06-21",
    "meta": "macOS app, Transcription, Whisper, Offline",
    "summary": "I recently built Verbatim, a native macOS transcription app that runs Whisper locally and turns audio or video files...",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-16.html",
    "title": "The Ultimate Answer to Life, the Universe, and Everything",
    "date": "2026-04-12",
    "meta": "Essay, AI booming, LLM",
    "summary": "After years of research, I have finally arrived at the ultimate answer to life, the universe, and everything, and the...",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-7.html",
    "title": "My TOP 3 Movie",
    "date": "2026-04-03",
    "meta": "Movies, Personal Favorites",
    "summary": "These are three films I keep returning to when I want something quiet, beautiful, and emotionally memorable.",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-8.html",
    "title": "Abstract Accepted for JpGU-AGU Joint Meeting 2026",
    "date": "2026-04-03",
    "meta": "Conference, Oral Presentation, JpGU, AGU",
    "summary": "My abstract, Secondary Weakening in dm-Scale Laboratory Earthquakes: Frictional Origin or Rigid-Body Artifact?, has...",
    "categories": [
      "conference"
    ]
  },
  {
    "href": "Article-15.html",
    "title": "My Top 5 TV Series",
    "date": "2026-04-02",
    "meta": "TV series, Personal Favorites",
    "summary": "These are five series I have kept returning to over the years.",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-6.html",
    "title": "Japan Geoscience Union Meeting 2026",
    "date": "2026-02-09",
    "meta": "",
    "summary": "Conference-related pages and updates for my participation in the JpGU-AGU Joint Meeting 2026.",
    "categories": [
      "conference"
    ]
  },
  {
    "href": "Article-5.html",
    "title": "Gauss 2025 Reflection",
    "date": "2025-12-31",
    "meta": "",
    "summary": "A year marked by research, conferences, friendships, and a series of small moments that made 2025 feel both busy and...",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-4.html",
    "title": "Japan Geoscience Union Meeting 2025",
    "date": "2025-12-17",
    "meta": "",
    "summary": "Conference-related pages and updates for my participation in the Japan Geoscience Union Meeting 2025.",
    "categories": [
      "conference"
    ]
  },
  {
    "href": "Article-2.html",
    "title": "Goodbye, 2024 — A Letter To Myself, A Reflection",
    "date": "2025-01-01",
    "meta": "",
    "summary": "A personal walk through the months of 2024, from quiet ordinary days to the moments that ended up shaping my year more...",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-3.html",
    "title": "November Sky",
    "date": "2024-12-01",
    "meta": "",
    "summary": "November began with an endless Ising Model simulation. Then everyone started arguing about that overpass.",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-9.html",
    "title": "整個城市，都是我的自習室",
    "date": "2024-05-04",
    "meta": "",
    "summary": "四月的暴雨、五月的太陽，都讓人只想待在有空調的室內。前幾天開車經過國圖才發現我已經好幾年沒進國圖自習室了。",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-10.html",
    "title": "Let the Whole City be My Library",
    "date": "2024-05-04",
    "meta": "",
    "summary": "April downpours and May sunshine both make you want to stay somewhere air-conditioned.",
    "categories": [
      "translation"
    ]
  },
  {
    "href": "Article-11.html",
    "title": "改變聽音樂的習慣",
    "date": "2022-08-08",
    "meta": "",
    "summary": "在串流音樂幾乎壟斷一切的時代，重新思考我們如何聽音樂，也許不只是個人習慣問題，而是和創作者、載體與專輯本身都有關。",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-12.html",
    "title": "Changing the Way We Listen to Music",
    "date": "2022-08-08",
    "meta": "",
    "summary": "In an age when streaming seems to have absorbed music entirely, it may be worth asking whether the way we listen also...",
    "categories": [
      "translation"
    ]
  },
  {
    "href": "Article-13.html",
    "title": "臺北市兜風指南",
    "date": "2021-12-12",
    "meta": "",
    "summary": "如果兜風是一種讓人暫時脫離現實、重新感受城市與自己的方式，那麼在臺北，選對時間與道路就非常重要。",
    "categories": [
      "personal"
    ]
  },
  {
    "href": "Article-14.html",
    "title": "A Guide to Driving Around Taipei",
    "date": "2021-12-12",
    "meta": "",
    "summary": "If driving with no destination in mind is a way of stepping outside ordinary life for a while, then in Taipei the right...",
    "categories": [
      "translation"
    ]
  }
];
