from __future__ import annotations

import json
import re
from html import unescape
from pathlib import Path


SITE_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_FILE = SITE_ROOT / "articles-data.js"
SKIP_FILES = {"Article-1.html"}


def strip_tags(fragment: str) -> str:
    fragment = re.sub(r"<br\s*/?>", " ", fragment, flags=re.IGNORECASE)
    fragment = re.sub(r"</p>", " ", fragment, flags=re.IGNORECASE)
    fragment = re.sub(r"<[^>]+>", "", fragment)
    fragment = unescape(fragment)
    return " ".join(fragment.replace("\xa0", " ").split())


def extract_first(pattern: str, text: str) -> str:
    match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
    if not match:
        return ""
    return strip_tags(match.group(1))


def shorten(text: str, limit: int = 120) -> str:
    text = text.strip()
    if len(text) <= limit:
        return text

    sentence_match = re.match(rf"^(.{{1,{limit}}}[.!?])(?:\s|$)", text)
    if sentence_match:
        return sentence_match.group(1).strip()

    cutoff = text.rfind(" ", 0, limit)
    if cutoff == -1:
        cutoff = limit
    return text[:cutoff].rstrip(" ,;:") + "..."


def parse_first_body_paragraph(html: str) -> str:
    main_match = re.search(
        r'<main class="container article-layout".*?>(.*?)</main>',
        html,
        re.IGNORECASE | re.DOTALL,
    )
    if not main_match:
        return ""

    main_html = main_match.group(1)
    if "</header>" in main_html:
        main_html = main_html.split("</header>", 1)[1]

    for paragraph_match in re.finditer(r"<p(?:\s+[^>]*)?>(.*?)</p>", main_html, re.IGNORECASE | re.DOTALL):
        text = strip_tags(paragraph_match.group(1))
        if not text:
            continue
        if text.startswith("Posted on "):
            continue
        if text == "National Taiwan University":
            continue
        return text

    return ""


def infer_categories(title: str, meta_text: str, eyebrow: str) -> list[str]:
    haystack = " ".join([title, meta_text, eyebrow]).lower()
    categories: list[str] = []

    if any(token in haystack for token in ["jpgu", "agu", "joint meeting", "presentation", "conference abstract"]):
        categories.append("conference")
    elif "conference" in eyebrow.lower():
        categories.append("conference")

    if any(token in haystack for token in ["english version", "translation", "translated"]):
        categories.append("translation")

    if "conference" not in categories and "translation" not in categories:
        categories.append("personal")

    return categories


def build_entry(path: Path) -> dict[str, object] | None:
    html = path.read_text(encoding="utf-8")

    if re.search(r'<meta\s+name="archive"\s+content="skip"\s*/?>', html, re.IGNORECASE):
        return None

    title = extract_first(r"<h1[^>]*>(.*?)</h1>", html)
    meta_text = extract_first(r'<(?:div|p)\s+class="meta"[^>]*>(.*?)</(?:div|p)>', html)
    eyebrow = extract_first(r'<header class="article-hero".*?<p class="eyebrow"[^>]*>(.*?)</p>', html)
    date_match = re.search(r"Posted on\s+(\d{4}-\d{2}-\d{2})", meta_text, re.IGNORECASE)

    if not title or not date_match:
        return None

    if "example article" in title.lower():
        return None

    keyword_match = re.search(r"Keywords:\s*(.+)$", meta_text, re.IGNORECASE)
    if keyword_match:
        summary = keyword_match.group(1).strip()
    else:
        summary = extract_first(r'<p class="lead"[^>]*>(.*?)</p>', html) or parse_first_body_paragraph(html)

    summary = shorten(summary)
    categories = infer_categories(title, meta_text, eyebrow)

    return {
        "href": path.name,
        "title": title,
        "date": date_match.group(1),
        "summary": summary,
        "categories": categories,
    }


def main() -> None:
    entries: list[dict[str, object]] = []

    for path in sorted(SITE_ROOT.glob("Article-*.html")):
        if path.name in SKIP_FILES:
            continue

        entry = build_entry(path)
        if entry:
            entries.append(entry)

    entries.sort(key=lambda item: (item["date"], item["title"]), reverse=True)

    payload = (
        "// This file is generated by tools/generate_articles_data.py\n"
        f"window.ARTICLE_INDEX = {json.dumps(entries, ensure_ascii=False, indent=2)};\n"
    )
    OUTPUT_FILE.write_text(payload, encoding="utf-8")


if __name__ == "__main__":
    main()
